repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.9.1
    hooks:
    - id: ruff
      args:
        [
          "--fix",
          "--exit-non-zero-on-fix"
        ]
    - id: ruff-format
  - repo: https://github.com/crate-ci/typos
    rev: v1.16.20
    hooks:
    - id: typos
      stages: [commit]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []

