name: Continuous Deployment

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release-build:
    name: Build release distributions 🔨👷
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      contents: write
      id-token: write 
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set the release version
        shell: bash
        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install hatch
        run: |
          python -m pip install hatch

      - name: Build release distributions
        run: |
          # NOTE: put your own distribution build steps here.
          python -m pip install hatch
          python -m hatch build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish to GitHub
        if: ${{ !contains(github.ref, '-') }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          file_glob: true
          overwrite: true
          tag: ${{ github.ref }}
          release_name: "Release v${{ env.RELEASE_VERSION }}"
          body: "${{ needs.generate-changelog.outputs.release_body }}"

      - name: Publish to GitHub (pre-release)
        if: ${{ contains(github.ref, '-') }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          file_glob: true
          overwrite: true
          tag: ${{ github.ref }}
          release_name: "Pre-release v${{ env.RELEASE_VERSION }}"
          prerelease: true

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
