# https://docs.astral.sh/ruff/integrations/#github-actions
name: CI

on: push

env:
  MAIN_BRANCH: main

jobs:
  precommit:
    name: Pre-commit 🔥
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.1

  test:
    name: "tests & coverage 💊"
    needs: precommit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Hatch
      run: pip install -U hatch

    - name: Tests
      run: hatch run +py=${{ matrix.python-version }} test:test


